version: '2'
services:

  database:
    image: mysql:5.7
    container_name: database
    volumes:
      - ./docker/database/dumps:/dumps:rw,cached
      - ./docker/database/data/mysql-master:/var/lib/mysql:rw,cached
      - ./docker/database/config/mysql-master:/etc/mysql/conf.d:rw,cached
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_MASTER_ROOT_PASSWORD}
    expose:
      - "3306"
    ports:
      - "3306:3306"
    restart: always